spring:
  # Mysql 的数据库配置
  datasource:
    url: jdbc:mysql://localhost:3305/springdb?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

